//include everything so we only need to include 3DEngine.h
#include "mesh.h"
#include "shader.h"
#include "basicShader.h"
#include "SkyboxShader.h"
#include "transform.h"
#include "camera.h"
#include "gameObject.h"
#include "meshRenderer.h"
#include "window.h"
#include "Engine.h"
#include "Input.h"
#include "game.h"
#include "Skybox.h"